apiVersion: v1
kind: Service
metadata:
  name: simpleapp
  labels:
    app: acme
    service: simpleapp
spec:
  ports:
    - name: http-simpleapp
      protocol: TCP
      port: 8080
  selector:
    app: acme
    service: simpleapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp
  labels:
    app: acme
    service: simpleapp
spec:
  selector:
    matchLabels:
      app: acme
      service: simpleapp
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: acme
        service: simpleapp
    spec:
      containers:
      - image: gcr.io/vmwarecloudadvocacy/simpleapp:1.0.0
        name: simpleapp'
        ports:
        - containerPort: 8080
          name: simpleapp


