apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: workshop-deployment
  labels:
    app: workshop-node
spec:
  selector:
    matchLabels:
      app: workshop
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: workshop
    spec:
      containers:
      - image: gcr.io/vmwarecloudadvocacy/simpleapp:latest
        name: workshop-node
        ports:
        - containerPort: 8080
          name: web-port
