apiVersion: v1
kind: Service
metadata:
  name: workshop-svc
  labels:
    app: workshop-node
spec:
  ports:
    - name: express-server
      protocol: TCP
      port: 8080
      nodePort: 30400
  selector:
    app: workshop
  type: NodePort
